networks:
  ml-battle-network:
    driver: bridge

services:
  ml_battle_website:
    container_name: ml_battle_website
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - ml-battle-network
    ports:
      - '80:80'
    volumes:
      - './src:/var/www'
      - './logs:/var/log/apache2'
    restart: always
